# Generated by Django 6.1.1 on 2026-09-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='request_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
